import { type NextPage, type NextPageContext } from "next";
import Head from "next/head";
import axios from "axios";
import { env } from "../env/server.mjs";
import { type IUser } from "./_app";
import nookies from "nookies";
import { Header, Sidebar, BottomNav } from "../components";

export async function getServerSideProps(ctx: NextPageContext) {
  try {
    const { userToken } = nookies.get(ctx);
    if (!userToken) {
      return {
        redirect: {
          permanent: false,
          destination: "/login",
        },
        props: {},
      };
    }

    const res = await axios.get(`${env.NEXT_PUBLIC_API_HOST}/users/profile`, {
      headers: {
        Authorization: `Bearer ${userToken}`,
      },
    });
    return {
      props: {
        user: (res.data as { user: IUser }).user,
      },
    };
  } catch (err) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
      props: {},
    };
  }
}

type Props = {
  user?: IUser;
};

const Home: NextPage = ({ user }: Props) => {
  return (
    <>
      <Head>
        <title>Frameflow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col dark:bg-black dark:text-neutral-100 sm:flex-row">
        {/* Header and BottomNav only for mobile, Sidebar only for bigger than mobile */}
        <Header />
        <Sidebar user={user as IUser} />
        <main className="flex-1 sm:flex sm:flex-grow-0">
          {/* main scroll */}
        </main>
        <div className="hidden lg:flex">{/* latest users */}</div>
        <BottomNav username={user?.username as string} />
      </div>
    </>
  );
};

export default Home;
