import { type NextPage, type NextPageContext } from "next";
import Head from "next/head";
import axios from "axios";
import { env } from "../env/server.mjs";
import { type IUser } from "./_app";
import nookies from "nookies";

export async function getServerSideProps(ctx: NextPageContext) {
  try {
    const { userToken } = nookies.get(ctx);
    if (!userToken) {
      return {
        props: {},
      };
    }

    const res = await axios.get(`${env.NEXT_PUBLIC_API_HOST}/users/profile`, {
      headers: {
        Authorization: `Bearer ${userToken}`,
      },
    });
    return {
      props: {
        user: res.data as IUser,
      },
    };
  } catch (err) {
    return {
      props: {},
    };
  }
}

type Props = {
  user?: IUser;
};

const Home: NextPage = ({ user }: Props) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col"></main>
    </>
  );
};

export default Home;
